### ISSUE TITLE
Double names after pressing "Thanks"

### ISSUE THREAD

**Issue by coreice** [Naguissa/thanks_for_posts#8]
Since version 4.0.2 I notice a rather strange issue. If you press the 👍 for a thanks on a post which already has one or more likes, the names get duplicated. This gives something like this (for both images I am the user "Mark").

![image](https://user-images.githubusercontent.com/10442497/210880864-82401c85-e7ef-4bba-9590-89149c550e56.png)

![image](https://user-images.githubusercontent.com/10442497/210881029-d9cdf627-e5fa-4c40-a1b6-da870cd0323e.png)

After a refresh of the page, the double names are gone.

Today I updated to version 4.0.4. but the issue is still there. Except for a (Dutch) translation I have not made any modifications to the extension.

Not sure what kind of information you need further. If you need more, I am happy to provide it!

**Comment by Naguissa** [comment]
Fixed on 4.0.5 release.
